### ISSUE TITLE
Cloudflare gives 404:

### ISSUE THREAD

**Issue by morrisb74** [deadbeef3137/ha-cloudflare-tunnel-monitor#10]
This error originated from a custom integration.

Logger: custom_components.cloudflare_tunnel_monitor.sensor
Source: custom_components/cloudflare_tunnel_monitor/sensor.py:70
Integration: Cloudflare Tunnel Monitor (documentation, issues)
First occurred: 10:42:13 (8 occurrences)
Last logged: 11:19:40

Error fetching Cloudflare tunnels: 404

**Comment by deadbeef3137** [comment]
If you have updated from version 1.0.0 to 2.0.0, it is necessary to reconfigure the integration, now Cloudflare API Tokens are used.
Check issue #8

**Comment by morrisb74** [comment]
It was a clean install today.
So no update.

**Comment by deadbeef3137** [comment]
Hello @morrisb74 .
Please, reinstall the new version 2.1.0 from scratch.

**Comment by morrisb74** [comment]
Did the reinstall but same error and no entities pop up:
Logger: custom_components.cloudflare_tunnel_monitor.sensor
Source: custom_components/cloudflare_tunnel_monitor/sensor.py:38
Integration: Cloudflare Tunnel Monitor ([documentation](https://github.com/deadbeef3137/ha-cloudflare-tunnel-monitor/blob/master/README.md), [issues](https://github.com/deadbeef3137/ha-cloudflare-tunnel-monitor/issues))
First occurred: 17:40:26 (1 occurrences)
Last logged: 17:40:26

Error fetching Cloudflare tunnels: 404

Anything I can add to help with debugging?

**Comment by deadbeef3137** [comment]
As for debugging, add these lines to your configuration.yaml file:

logger:
  default: warning
  logs:
    custom_components.cloudflare_tunnel_monitor: debug

Have you created an API Token in Cloudflare with read permissions for the tunnels?

![image](https://github.com/deadbeef3137/ha-cloudflare-tunnel-monitor/assets/91840166/1365c2e7-5980-4548-83f5-94e4e96ac6ad)

**Comment by happy-chap** [comment]
Can confirm I'm seeing the same 404 error with a new install this evening of v2.1.0 and I have created an API key as per the instructions.

From the log:
2024-01-22 21:55:34.221 DEBUG (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Fetching new tunnel data from Cloudflare
2024-01-22 21:55:34.328 DEBUG (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Response status: 404
2024-01-22 21:55:34.328 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching Cloudflare tunnels: 404
2024-01-22 21:55:34.330 DEBUG (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Added tunnels: [], Removed tunnels: []
2024-01-22 21:55:34.330 DEBUG (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Finished fetching cloudflare_tunnel data in 0.109 seconds (success: True)
2024-01-22 21:55:34.331 DEBUG (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Creating initial sensor entities

API Token in Cloudflare:
<img width="997" alt="image" src="https://github.com/deadbeef3137/ha-cloudflare-tunnel-monitor/assets/78432558/2fe8375a-41ff-4d89-9d70-0219e190e660">

**Comment by deadbeef3137** [comment]
I can't replicate your error.
In the integration, enable debug logging, reconfigure the integration, and load the full logs in the logs section. 
Don't make them public by sending them here, they contain sensitive data like the public IP, Account ID, User ID, etc.
That's strange, if your user has the necessary permissions, and the token and Account ID are correct, there shouldn't be any problem, at least for creating entities for the tunnels you already have.

**Comment by morrisb74** [comment]
After setting the debug options, that's all there is showing up in the log (and yes HA has been restarted ;-) )

**Comment by happy-chap** [comment]
Thanks, I'd already done that and pasted the Cloudflare Tunnel Monitor entries from the full logs above. 

Unless I am misunderstanding you?

Incidentally, if I manually verify the token (there's a curl example on the API token creation page in Cloudflare) it confirms the API is valid and active, and I only have a single user on my Cloudflare account, which is set as Super Admin, so I would assume has the necessary permissions.

**Comment by deadbeef3137** [comment]
I just restarted the Home Assistant and got that error (the entities were no longer available, but reloading the integration manually made it work normally again).
There's probably a bug in the function that retrieves the tunnels, I'm going to release a new version and hope it gets fixed, because I can't replicate it when I want to, it randomly appears on some system restarts.

**Comment by happy-chap** [comment]
Actually, in my case @deadbeef3137 it looks like my error. I was using my account profile instead of account ID. I've now recreated the integration correctly with account ID and it's working :-) So sorry, my error.

Just a thought @morrisb74 but have you made the same mistake as me? account ID that this integration needs can be found using these instructions -> https://developers.cloudflare.com/fundamentals/setup/find-account-and-zone-ids/

**Comment by morrisb74** [comment]
Yep, that was it ... Ok, might be an idea to add specific info to the docs where to find it (as normally your account is your email address :D )
