### ISSUE TITLE
Tunnel unavailable

### ISSUE THREAD

**Issue by jrockstedt** [deadbeef3137/ha-cloudflare-tunnel-monitor#11]
I have three tunnels that I want to monitor, but integration are loosing the status "connection to cloudflare" of tunnels and they stay as "Unavailable"
I have reconfigured it again and only have one device.
If I reload the integration they are going back to healthy.

**Comment by jrockstedt** [comment]
![image](https://github.com/deadbeef3137/ha-cloudflare-tunnel-monitor/assets/81170681/6b79a7d8-7891-4ad2-a325-5a249b71df13)

**Comment by deadbeef3137** [comment]
If you have updated from 2.0.0, I recommend reinstalling the integration from scratch. In v2.1.0, there were significant changes in the code base, now all tunnels are grouped into a single device. This allows for easier removal of old tunnels.
Regarding the connection status error, I detected it last night and have implemented a retry strategy to prevent it from happening, and in my case, it seems to be working correctly.
If, despite reinstalling the integration, you continue to get this error, let me know and we'll try to solve it as soon as possible.

**Comment by jrockstedt** [comment]
I just upgraded to 2.1.3, lets see if this make it stable.

**Comment by deadbeef3137** [comment]
In my case, when that happens, everything goes back to normal on the second try. I'll try to figure out why this is happening to fix it in future versions.
![log](https://github.com/deadbeef3137/ha-cloudflare-tunnel-monitor/assets/91840166/2028756a-e026-4325-b407-9851b556dc1f)

**Comment by jrockstedt** [comment]
Version 2.1.3 is working much better now.
Thank you for the support. :-)

**Comment by deadbeef3137** [comment]
I have worked on a new version and so far no more logs have appeared, in v2.1.3 although it works better due to the retries, sometimes the entities become unavailable.
Please update to 2.1.4.

**Comment by jrockstedt** [comment]
Upgrade completed to 2.1.4
