### ISSUE TITLE
Request - Tunnel version

### ISSUE THREAD

**Issue by minesh48** [deadbeef3137/ha-cloudflare-tunnel-monitor#13]
Hi. Am not sure if this possible. 

Is there away to get the version of a tunnel software being used or if there is new version in to HA? So I get a notification to upgrade to latest version

**Comment by deadbeef3137** [comment]
Hello @minesh48, Thank you very much for your feedback.
I'll keep that in mind for future versions. Currently, to view the tunnel version and latest version, you can create two sensors in your configuration.yaml with the following code:
`
sensor:
  - platform: template
    sensors:
      cloudflared_version:
        friendly_name: "Tunnel Version"
        value_template: "{{ state_attr('update.cloudflared_update', 'installed_version') }}"
      latest_version:
        friendly_name: "Cloudflared Latest Version"
        value_template: "{{ state_attr('update.cloudflared_update', 'latest_version') }}"
`

Once the sensors are created, you'll need to restart your Home Assistant and create an automation that calls Home Assistant's notification service, a Telegram bot, etc. 

P.D.: If you need help setting up the notification service of your choice, let me know.

**Comment by minesh48** [comment]
Thank you.  I think I got it working just need to wait for new version for a a full test

**Comment by derekoharrow** [comment]
I'm running v2.1.6 of this on HA 2024.07.1 and I don't see the update.cloudflared_update sensors. How do I get them to appear?
ta

**Comment by deadbeef3137** [comment]
Hello @derekoharrow ,

The Cloudflare Tunnel Monitor integration has no relation to the Cloudflared addon, they have been developed by different people. 

If you have any issues with Cloudflared, please contact the developer of the Cloudflared addon [https://github.com/brenner-tobias/addon-cloudflared/issues](https://github.com/brenner-tobias/addon-cloudflared/issues)

P.D.: This integration automatically updates the status of the sensors (tunnels) every minute. Each time you create a tunnel, the integration detects it and adds it to your list of sensors.

Anyway, if you still want to update the tunnels, you can manually reload the integration.
