### ISSUE TITLE
(no issue) Remove old tunnels

### ISSUE THREAD

**Issue by poudenes** [deadbeef3137/ha-cloudflare-tunnel-monitor#3]
Hi There,

Great integration. In past I was testing a lot how tunnels working etc. Used RPI, my iMac etc... Now I'm settled and my tunnel is running perfect on my NAS.

After the integration has been done I see lots of old inactive tunnels. On the Portal of Cloudflare I can't find them.

Do you know maybe how I can remove those old tunnels with all kind of names: test, rpi4test, cf-test etc etc...

Greets

**Comment by deadbeef3137** [comment]
Hello @poudenes,
Thank you very much for your comment. It's a small error in the integration, I need to add a parameter to remove the old tunnels from the API.
Sorry for the inconvenience. Lately, I haven't had much time, but I'll get it fixed this week.

**Comment by deadbeef3137** [comment]
Thank you very much @jorgwolski.

**Comment by deadbeef3137** [comment]
Please, reinstall the new version 2.1.0 from scratch.

1. An automated manager has been implemented to add new tunnels without the need for manual reloading of the integration.
2. Tunnels are now grouped under a single device.
3. It is now possible to remove old tunnels.
4. New debug logs have been added to enhance error traceability.

**Comment by pippo73** [comment]
Thank you, the 2.1.3 release fixed the problem :-)
