### ISSUE TITLE
No entities after API key changes

### ISSUE THREAD

**Issue by jorgwolski** [deadbeef3137/ha-cloudflare-tunnel-monitor#7]
After updating to 2.0.0 and reauthenticating, login works, but no devices/entities are created for the tunnels.

**Comment by deadbeef3137** [comment]
Try uninstalling the old version, restart Home Assistant, and install the new version.
I just installed it from HACS, and it's working fine for me.

**Comment by deadbeef3137** [comment]
That's strange... Did you create the token with read permissions for Cloudflare tunnels?

![imagen_2024-01-17_102843479](https://github.com/deadbeef3137/ha-cloudflare-tunnel-monitor/assets/91840166/c92f5140-de76-4689-8e69-799e5a3ec8ff)
