### ISSUE TITLE
v2.0.0 - Email field missing

### ISSUE THREAD

**Issue by poudenes** [deadbeef3137/ha-cloudflare-tunnel-monitor#8]
The new version 2.0.0 doesn't have the email field anymore. I removed the integration to get rid of the old (not used) tunnels.
After I want setup the integration this email filed was gone.

Cleared cache, restart safari didn't help as well

**Comment by deadbeef3137** [comment]
There has been an improvement in security; now, neither the email nor the Global API is used. Instead, the Account ID and an API token that you have to create in Cloudflare are used.
You need to create a custom token.
![imagen_2024-01-17_110238764](https://github.com/deadbeef3137/ha-cloudflare-tunnel-monitor/assets/91840166/334ae5fb-0834-4bdc-be5d-72b6327cc45e)

**Comment by poudenes** [comment]
Done and working!
